# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Western Mari spellchecker"
mrj = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Western Mari, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
mrj = "TRANSLATE: A spellchecker for Western Mari, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.mrj"

[windows]
system_product_code = "{7D83D1BA-3E24-4704-816B-28E6457D84F9}_is1"
legacy_product_codes = [
    { value = "C1F02079-F538-4511-B713-70C0F06E5CDC", kind = "nsis" },
    { value = "6D055FC3-18F2-46AD-9A63-D547BDB89888", kind = "nsis" }
]

[package.speller]
name = "Western Mari"
version = "0.1.1"

[package.grammar]
name = "Western Mari"
version = "0.1.0"

[package.tts-text-proc]
name = "Western Mari"
version = "0.1.0"
