template = "https://github.com/giellalt/template-lang-und"
rev_id = 256
template_sha = "4e2ddf168a2aaf68d2c29db9e79e44e1dc4c2b76"

[replacements]
__GLOTTOLOG_ID__ = "west2392"
__REPO__ = "lang-mrj"
__UND2C__ = "mrj"
__UNDEFINED__ = "Western Mari"
__UND__ = "mrj"
