template = "https://github.com/giellalt/template-lang-und"
rev_id = 277
template_sha = "c0f383639e245d1daebce6e2006904e442eef1fd"

[replacements]
__GLOTTOLOG_ID__ = "west2392"
__REPO__ = "lang-mrj"
__UND2C__ = "mrj"
__UNDEFINED__ = "Western Mari"
__UND__ = "mrj"
